Vagrant.configure(2) do |config|
  
  config.vm.box = "laravel/homestead"
  config.vm.box_version = "11.0.0"

  config.vm.network "private_network", ip: "192.168.51.53"

  config.vm.synced_folder "../dev_box", "/vagrant", :owner => 'vagrant', :group => 'www-data'
  config.vm.synced_folder "../html", "/var/www/html", :owner => 'vagrant', :group => 'www-data'
  config.vm.synced_folder "../log", "/var/www/log", :owner => 'vagrant', :group => 'www-data'

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "shell", path: "./provision.sh"

end